# Generated by Django 4.2.3 on 2023-08-11 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_coursesubscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSubscribe',
            new_name='CourseSubscription',
        ),
    ]
